# Generated by Django 4.0 on 2021-12-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=30)),
                ('summary', models.TextField(max_length=100)),
                ('author', models.CharField(max_length=30, null=True)),
                ('genre', models.CharField(max_length=30, null=True)),
                ('isbn', models.IntegerField(null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Denied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('book_id', models.IntegerField()),
                ('reason', models.TextField()),
                ('book_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('book_id', models.IntegerField()),
                ('time', models.IntegerField(default=7)),
                ('book_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Issued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('book_id', models.IntegerField()),
                ('time', models.IntegerField(default=7)),
                ('book_name', models.CharField(max_length=30)),
            ],
        ),
    ]
